CREATE DATABASE IF NOT EXISTS enterprise;
USE enterprise;

#ALMACENADO DE DATOS 
# CREAMOS LA TABLA EMPLEADOS

CREATE TABLE IF NOT EXISTS empleados(
Id_empleado INT UNIQUE NOT NULL PRIMARY KEY,
Nombre_empleado VARCHAR (30) NOT NULL,
Salario DECIMAL(10,2)
);
