#PROCEDIMIENTO PARA CONTAR CUANTOS EMPLEADOS HAY EN LA TABLA 
DELIMITER //

CREATE PROCEDURE contar_empleados()
BEGIN
    SELECT COUNT(*) AS total_empleados # SE USA EL * PORQUE NO ESTOY CONTANDO CON UN ATRIBUTO ESPECIFICO, YA QUE SE BUSCA QUE SE CUENTE EL TOTAL DE EMPLEADOS Y ACOMPAÑADO DE UN ALIAS
    FROM empleados;
END //

DELIMITER ;
CALL contar_empleados();
